### ISSUE TITLE
Front End edit image form badly broken

### ISSUE THREAD

**Issue by N6REJ** [N6REJ/ae-template#56]
its a complete mess.. buttons missing, form badly laid out, etc...
Not sure why modal is even there.
check against standard joomla to see what is different.
![intro-image-form](https://cloud.githubusercontent.com/assets/1850089/5866298/88992148-a255-11e4-9074-f00c5578ef56.JPG)

**Comment by MaxOnTheHill** [comment]
@N6REJ hey Troy .. back after being super sick for a while ... how'd you go with the form stuff ... did you actually find a fix in the commits, or is it still problematic?
Thx, Max

**Comment by N6REJ** [comment]
I lost my local server for a bit and haven't gotten any further.. Ammps 
update totally destroyed my db... but I had not found a complete fix, 
just cludging....
all the normal "contact" forms i've had to rewrite to work with BS3 and 
its not completely finished... don't really like the layout for sliders 
info section.
Bear

**Comment by MaxOnTheHill** [comment]
@N6REJ yep ... the different contact form layouts don't seem to have been covered in the Joostrap backbone code ... and need to finally sort out what's happening with the (image & other) forms.
Thanks for feedback  ... will let you know as I progress on this :)

**Comment by N6REJ** [comment]
I'm rewriting all of the contact forms.  Have some mostly done, but not 
all.. the image is the one we really need your resources on.
Bear

**Comment by N6REJ** [comment]
This issue was moved to N6REJ/embryo#60
